# Generated by Django 5.1 on 2024-09-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_alter_userextend_phone_alter_userextend_rt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=100)),
                ('info_description', models.TextField()),
                ('info_created_date', models.DateField()),
                ('info_image', models.ImageField(upload_to='')),
                ('edited', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userextend')),
            ],
        ),
    ]
