# Generated by Django 5.1 on 2024-09-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_desa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='information',
            name='revision',
            field=models.BooleanField(default=False),
        ),
    ]
