# Generated by Django 5.1 on 2024-09-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_desa', '0002_information_approved_information_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='user_id',
            new_name='user',
        ),
    ]
