# Generated by Django 5.1 on 2024-09-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_desa', '0003_rename_user_id_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info_image',
            field=models.BinaryField(),
        ),
    ]
