# Generated by Django 5.1 on 2024-09-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_desa', '0004_alter_information_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
