# Generated by Django 5.1 on 2024-09-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_desa', '0005_information_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rejected', 'rejected'), ('revision', 'revision')], max_length=8)),
                ('message', models.TextField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_desa.information')),
            ],
        ),
    ]
