# Generated by Django 5.1 on 2024-09-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_desa', '0006_informationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info_image',
            field=models.BinaryField(null=True),
        ),
    ]
