# Generated by Django 5.1 on 2024-09-07 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_rename_user_id_userextend_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_target', models.CharField(max_length=50)),
                ('edited', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('revision', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userextend')),
            ],
        ),
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rejected', 'rejected'), ('revision', 'revision')], max_length=8)),
                ('message', models.TextField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_desa.event')),
            ],
        ),
    ]
