# Generated by Django 5.1 on 2024-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='rt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='rw',
            field=models.IntegerField(),
        ),
    ]
