# Generated by Django 5.1 on 2024-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_userextend_rt_alter_userextend_rw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='user_type',
            field=models.CharField(choices=[('super_user', 'super_user'), ('special_user', 'special_user'), ('special_user_rw', 'special_user_rw'), ('user', 'user'), ('visitor', 'visitor')], default='user', max_length=20),
        ),
    ]
