# Generated by Django 5.1 on 2024-09-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_alter_userextend_rt_alter_userextend_rw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userextend')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('pregnant', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('work', models.BooleanField(default=False)),
                ('rt', models.SmallIntegerField()),
                ('rw', models.SmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.batch')),
            ],
        ),
    ]
