# Generated by Django 5.1 on 2024-09-08 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_batch_approved_batch_date_batch_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 23, 30, 822979, tzinfo=datetime.timezone.utc)),
        ),
    ]
