# Generated by Django 5.1 on 2024-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_batchmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='work',
            field=models.CharField(choices=[('student', 'student'), ('unemployed', 'unemployed'), ('employee', 'employee')], max_length=10),
        ),
    ]
