# Generated by Django 5.1 on 2024-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_resident_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='work',
            field=models.CharField(choices=[('student', 'student'), ('unemployed', 'unemployed'), ('employee', 'employee')], default='unemployed', max_length=10),
        ),
    ]
